variables:
  DOCKER_IMAGE: "docker:stable"
  PAGES_URL: https://noobmaster669.gitlab.io/-/gg-bot-upload-assistant/


include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
- local: .gitlab-ci/*.gitlab-ci.yml

stages:
- build
- test
- deploy
