variables:
  DOCKER_IMAGE: "docker:stable"

include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
- local: .gitlab-ci/*.gitlab-ci.yml

stages:
- build
- test
- deploy
