# GG Bot Upload Assistant
# Copyright (C) 2022  Noob Master669

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

variables:
  DOCKER_IMAGE: docker:stable
  PAGES_URL: https://noobmaster669.gitlab.io/-/gg-bot-upload-assistant/

include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
- local: ".gitlab/ci/*.gitlab-ci.yml"
- template: Security/Dependency-Scanning.gitlab-ci.yml

stages:
- experiment
- lint
- build
- test
- verify
- deploy

release-set:
  stage: test
  image: noobmaster669/gg-bot-base:test-latest
  variables:
    SOURCE_DIRECTORY: gg-bot-upload-assistant
  script:
    - echo "${CI_COMMIT_TAG:-$CI_COMMIT_SHA}" > RELEASE
  artifacts:
    paths:
      - RELEASE
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


windows_tests:
  image: mcr.microsoft.com/windows/python:3.9
  stage: experiment
  tags:
    - windows
  before_script:
    - pip install -r requirements/requirements_test.txt
    - pip freeze > requirements/requirements_test.txt
  script:
    - pytest -vv --show-capture=stdout --cov-report=html --junitxml=junit_report.xml --cov=./ tests/
    