variables:
  DOCKER_IMAGE: "docker:stable"

stages:
- build
- test
- deploy

include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
- local: cicd/.gitlab-ci-base-images.yml
- local: cicd/.gitlab-ci-unit-test.yml
- local: cicd/.gitlab-ci-uploaders.yml