repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "^po/"
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-ast
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: codespell
        name: check for misspellings
        description: Check for common misspellings in text files
        args:
          [
            --check-hidden,
            --check-filenames,
            -L,
            'te,tha',
            --skip=*.po,
            --builtin,
            clear,
            rare,
            informal,
            usage,
            code,
          ]
        language: system
        entry: poetry run codespell
        types: [text]
      - id: add-license-header
        name: add license header
        description: Add the required license header to Python files if missing
        language: script
        entry: ./hooks/add_license_header.py
        types: [python]
