repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "^po/"
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-ast
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: codespell
        name: check for misspellings
        description: Check for common misspellings in text files
        args:
          [
            --check-hidden,
            --check-filenames,
            -L,
            'te,tha',
            --skip=*.po,
            --builtin,
            clear,
            rare,
            informal,
            usage,
            code,
          ]
        language: system
        entry: poetry run codespell
        types: [text]
#      - id: pyupgrade
#        name: check for old python syntax
#        description: Automatically upgrade syntax for newer versions
#        args: [--py36-plus, --keep-runtime-typing]
#        language: system
#        entry: poetry run pyupgrade
#        types: [python]
