# ********************************************** #
# ********************************************** #
#                Unit Tests GG-BOT               #
# ********************************************** #
# ********************************************** #
unit-test:
  stage: test
  image: noobmaster669/gg-bot-base:test-latest
  script:
    - pip install -r requirements/requirements_test.txt
    - pip freeze > requirements/requirements_test.txt
    # - pytest -vv --show-capture=stdout --cov-report=html --cov-report=xml --junitxml=junit_report.xml --cov=./ .
    - pytest -vv --show-capture=stdout --cov-report=html --junitxml=junit_report.xml --cov=./ .
    - coverage report
    - coverage xml -o coverage.xml
    - sed -i 's|" filename="|" filename="src/|g' coverage.xml
    # sending coverage report to codecov
    - curl -Os https://uploader.codecov.io/latest/alpine/codecov
    - chmod +x codecov
    - ./codecov -R .
    # sending coverage report for codacy
    - bash <(curl -Ls https://coverage.codacy.com/get.sh)
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - coverage.xml
      - coverage
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit:
        - junit_report.xml
    expire_in: 30 days

sast:
  stage: test
