# ********************************************** #
# ********************************************** #
#                Unit Tests GG-BOT               #
# ********************************************** #
# ********************************************** #
unit-test:
  stage: test
  image: noobmaster669/gg-bot-base:test-latest
  script:
    - pip install -r requirements/requirements_test.txt
    - pip freeze > requirements/requirements_test.txt
    # - pytest -vv --show-capture=stdout --cov-report=html --cov-report=xml --junitxml=junit_report.xml --cov=./ .
    - pytest -vv --show-capture=stdout --cov-report=html --junitxml=junit_report.xml --cov=./ .
    # - sed -i 's|" filename="|" filename="src/|g' coverage/coverage.xml
    - coverage xml -o coverage/coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml
      junit:
        - junit_report.xml
    paths:
      - coverage
    expire_in: 30 days
