# GG Bot Upload Assistant
# Copyright (C) 2022  Noob Master669

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Docker compose for GG-Bot Auto Uploader
# please note that this compose file cannot be used with GG-Bot Upload Assistant
# ------------------------------------
# To use this compose file, you'll need to create the following file in the location where you have this compose file
# and provide values for the following variables (samples for all these files are available in the env-files-samples folder)
#
# .env file           -> variables for docker-compose
# .transmission.env   -> transmission related environment variables
# reupload.config.env -> gg-bot reuploader configurations
#
services:
  mongo:
    image: mongo:${MONGO_VERSION}
    hostname: mongo
    restart: unless-stopped
    command: ["--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
    volumes:
      - ${BASE_PATH}/apps/mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .mongo_express.env
    depends_on:
      - mongo

  transmission:
    image: lscr.io/linuxserver/transmission:${TRANSMISSION_VERSION}
    hostname: transmission
    restart: unless-stopped
    env_file:
      - .transmission.env
    volumes:
      - ${BASE_PATH}/apps/transmission/config:/config
      - ${BASE_PATH}/data/downloads:/downloads
      - ${BASE_PATH}/data/watch:/watch
    ports:
      - ${TRANSMISSION_WEBUI_PORT}:9091
      - ${TRANSMISSION_PORT_51413}:51413
      - ${TRANSMISSION_PORT_51413}:51413/udp
  gg-bot-auto-uploader:
    image: noobmaster669/gg-bot-uploader:${GG_BOT_REUPLOADER_VERSION}
    restart: unless-stopped
    hostname: gg-bot-reuploader
    tty: true
    # change the below volume mapping according to your torrent client
    volumes:
      - ${BASE_PATH}/data/downloads:/downloads
    ports:
      - ${VISOR_SERVER_PORT}:30035
    env_file:
      - reupload.config.env
    # based on your configuration the gg-bot-auto-uploader will depend on either mongo or redis
    # if using mongo comment out redis, and vice-versa
    depends_on:
      - mongo
      - transmission
    # provide the list of trackers to upload to here
    # TODO see how this can be taken from the .env file
    command: [ "-t", "<TRACKERS>", "<OPTIONAL_ARGUMENTS>" ]
