# GG Bot Upload Assistant
# Copyright (C) 2022  Noob Master669

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Image ID: noobmaster669/gg-bot-uploader:{TAG}
# Image Description: Normal Docker Image build and stored in Docker Registry
# Build Conditions: On all tags and master branch
docker-hub-image-reuploader:
  stage: deploy
  image:
    name: $DOCKER_IMAGE
  services:
    - name: docker:dind
      alias: buildcontainer
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  variables:
    DOCKER_HOST: tcp://buildcontainer:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$DOCKER_CI_REGISTRY_USER" -p "$DOCKER_CI_REGISTRY_PASSWORD" $DOCKER_CI_REGISTRY
  script:
    - mv Dockerfiles/Dockerfile.reuploader ./
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":latest-reuploader"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest-reuploader'"
      elif [[ $CI_COMMIT_TAG ]]; then
        tag=":$CI_COMMIT_TAG-reuploader"
        echo "Running for tag '$CI_COMMIT_TAG': tag = $tag"
      else
        tag=":$CI_COMMIT_REF_SLUG-reuploader"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - |
      echo "Building Image '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker build --pull -t "$DOCKER_CI_REGISTRY_IMAGE${tag}" -f Dockerfile.reuploader .
    - |
      echo "Publishing Image to Docker Hub Container Registry: '$DOCKER_CI_REGISTRY_IMAGE${tag}"
    - docker push "$DOCKER_CI_REGISTRY_IMAGE${tag}"
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "dev"' # runs for every tags and master branch and dev branch
      exists:
        - Dockerfiles/Dockerfile.reuploader
